import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createEpisode } from '../episode.mjs';
import { createRecord, validateRecord, verifyCandidate, verifyRecord, transition, rejectRecord, DistillationStore, canonicalize, hashCanonical, hashArtifact, replayRecord, exportDataset, fromEpisode, verifyEpisodeLineage, VerifierRegistry, replayWithAdapter, registerReplayAdapter } from '../distillation.mjs';

const artifact = mkdtempSync(join(tmpdir(), 'kad-artifact-')) + '/source.txt';
writeFileSync(artifact, 'observed source\n');
const base = overrides => createRecord({ id: 'r1', task: { class: 'evidence', objective: 'report verification' }, provenance: { source: 'test', source_version: 'v1', executor: 'fixture', timestamp: '2026-01-01T00:00:00Z', source_artifact: artifact, source_hash: hashArtifact(artifact) }, input: { canonical: { task: 'run verifier' } }, behavior: { required: ['run verifier first'], forbidden: ['guess pass'] }, output: { expected_type: 'object', canonical_example: { verdict: 'PASS', exit: 0 } }, verification: { verifier_ids: ['record-schema'], evidence: [], verdict: 'UNKNOWN' }, replay: { enabled: true, adapter_id: 'fixture', fixture: { input: { value: 1 }, expected: { verdict: 'PASS', exit: 0 } }, comparison_mode: 'EXACT_OUTPUT' }, ...overrides });
const verified = (overrides = {}) => { const c = base(overrides); const v = verifyCandidate({ ...c, state: 'CANDIDATE', promotion: { ...c.promotion, state: 'CANDIDATE' } }); assert.equal(v.verified, true); return transition(v.record, 'VERIFIED'); };
const golden = (overrides = {}) => transition(verified(overrides), 'GOLDEN', { promoted_by: 'deterministic-policy', promotion_evidence: ['authorized receipt'] });

test('schema validation and canonicalization preserve meaningful whitespace', () => { const g = golden(); assert.equal(validateRecord(g).valid, true); assert.equal(validateRecord({ ...g, input: { ...g.input, hash: 'bad' } }).valid, false); assert.notEqual(canonicalize({ text: 'a b' }), canonicalize({ text: 'ab' })); assert.notEqual(hashCanonical({ text: 'a b' }), hashCanonical({ text: 'ab' })); });
test('forged receipt and unknown verifier fail closed', () => { const forged = base({ state: 'CANDIDATE', promotion: { state: 'CANDIDATE' }, verification: { verifier_ids: ['record-schema'], evidence: [{ verifier_id: 'record-schema', deterministic: true, passed: true }], verdict: 'PASS' } }); assert.equal(verifyRecord(forged).verified, false); assert.equal(verifyCandidate(base({ verification: { verifier_ids: ['unknown'], evidence: [], verdict: 'UNKNOWN' } })).verified, false); });
test('authorized verifier execution creates an authenticated receipt', () => { const registry = new VerifierRegistry().register('always-valid', candidate => ({ observed: candidate.input.canonical.task, expected: 'run verifier', passed: candidate.input.canonical.task === 'run verifier' })); const result = verifyCandidate(base({ verification: { verifier_ids: ['always-valid'], evidence: [], verdict: 'UNKNOWN' } }), registry); assert.equal(result.verified, true); assert.equal(typeof result.evidence[0].receipt_hash, 'string'); const tampered = { ...result.record, verification: { ...result.record.verification, evidence: [{ ...result.evidence[0], passed: false }] } }; assert.equal(verifyRecord(tampered, registry).verified, false); });
test('promotion requires verified evidence and provenance hash', () => { assert.throws(() => transition(base({ state: 'CANDIDATE', promotion: { state: 'CANDIDATE' } }), 'VERIFIED'), /verification/); const g = verified(); writeFileSync(artifact, 'tampered\n'); assert.throws(() => transition(g, 'GOLDEN', { promoted_by: 'gate', promotion_evidence: ['receipt'] }), /hash mismatch/); writeFileSync(artifact, 'observed source\n'); });
test('rejection is machine-readable and RAW cannot jump to GOLDEN', () => { assert.throws(() => transition(base(), 'GOLDEN'), /illegal transition/); const r = rejectRecord({ ...base(), state: 'CANDIDATE', promotion: { state: 'CANDIDATE' } }, { failure_class: 'TEST_FAILURE', failed_verifier: 'record-schema', observed: 1, expected: 0, lesson: 'do not report PASS on failure' }); assert.equal(r.rejection.failure_class, 'TEST_FAILURE'); });
test('replay requires fresh execution and mismatches fail', async () => { const g = golden(); assert.equal(replayRecord(g).status, 'NOT_REPLAYED'); assert.equal(replayRecord(g, { verdict: 'FAIL' }).status, 'FAIL'); registerReplayAdapter('fixture', async () => ({ verdict: 'PASS', exit: 0 })); assert.equal((await replayWithAdapter(g)).status, 'PASS'); });
test('Episode lineage is content-addressed and checked', () => { const episode = createEpisode({ episode_id: 'ep-real-1', task: { task_id: 'task-1', domain: 'RETRIEVAL', task_class: 'fact', objective: 'observe fact' }, resolution: { selected_execution_class: 'DETERMINISTIC_EXISTING', capability_id: 'file.read' }, validation: { validator: 'file-check', result: 'PASS' }, outcome: { accepted: true }, evidence_refs: ['observed-file.jsonl'] }); const candidate = fromEpisode(episode, { id: 'real-distill-1', input: { canonical: { task: 'observe fact' } }, verification: { verifier_ids: ['record-schema'] } }); assert.equal(verifyEpisodeLineage(candidate, episode).valid, true); assert.equal(verifyEpisodeLineage({ ...candidate, provenance: { ...candidate.provenance, source_episode_hash: 'bad' } }, episode).valid, false); });
test('training export is separate from runtime export', () => { const g = golden({ id: 'runtime-only' }); assert.equal(exportDataset([g], 'training'), ''); const approved = { ...g, id: 'approved', training_eligibility: { eligible: true, rights_status: 'ACCEPTED', quality_status: 'ACCEPTED' } }; assert.notEqual(exportDataset([approved], 'training'), ''); const rejected = rejectRecord({ ...base({ id: 'bad' }), state: 'CANDIDATE', promotion: { state: 'CANDIDATE' } }, { failure_class: 'HALLUCINATED_STATE' }); assert.equal(exportDataset([g, rejected]).includes('bad'), false); });
test('store and repeated export are deterministic', () => { const store = new DistillationStore(mkdtempSync(join(tmpdir(), 'kad-distill-'))); const g = golden({ id: 'stored' }); store.put(g); assert.equal(store.list('GOLDEN').length, 1); assert.equal(exportDataset(store.list()), exportDataset([...store.list()].reverse())); });
