import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { createEconomicPolicy, quotaNotification, routeEconomically } from '../economic-router.mjs';
import { normalizeQuota } from '../quota-state.mjs';
import { BoundedQuotaProbeCache, normalizeProviderProbeError, parseGitHubUsage, parseOpenAiCodexStatus, parseOpenRouterKey, declaredOpenCodeGoPolicy } from '../remote-quota-observation.mjs';
import { normalizeRawProviderQuota, redactProviderOutput } from '../provider-quota-adapter.mjs';

const now = Date.parse('2026-08-29T00:00:00Z');
const policy = { stale_ttl_ms: 86_400_000, expiring_window_ms: 86_400_000, green_min_fraction: 0.5, yellow_min_fraction: 0.25 };
const quotaWindow = (overrides = {}) => ({ window_id: 'weekly', unit: 'USD', capacity: 30, remaining: 20, status: 'KNOWN', confidence: 'OBSERVED', observed_at: now, ...overrides });
const lane = quota => ({ lane_id: 'remote', execution_class: 'REMOTE_SUBSCRIPTION', trust_domain: 'retrieval', capabilities: ['x'], context_window: 100, quota });

test('T1 multi-window normalization preserves each window independently', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: '5h', capacity: 12, remaining: 9 }), quotaWindow(), quotaWindow({ window_id: 'monthly', capacity: 60, remaining: 51 })] }, policy, now); assert.deepEqual(q.windows.map(w => w.window_id), ['5h', 'weekly', 'monthly']); assert.deepEqual(q.windows.map(w => w.capacity), [12, 30, 60]); });
test('T2 effective state uses the most restrictive compatible window', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: '5h', capacity: 12, remaining: 9 }), quotaWindow({ window_id: 'weekly', remaining: 0 }), quotaWindow({ window_id: 'monthly', capacity: 60, remaining: 50 })] }, policy, now); assert.equal(q.watermark, 'RED'); assert.equal(q.effective_window_id, 'weekly'); });
test('T3 declared capacity plus unknown usage stays UNKNOWN', () => { const q = normalizeQuota({ windows: [quotaWindow({ confidence: 'DECLARED', remaining: null, used: null })] }, policy, now); assert.equal(q.windows[0].capacity, 30); assert.equal(q.windows[0].remaining, null); assert.equal(q.windows[0].status, 'UNKNOWN'); assert.equal(q.windows[0].watermark, 'UNKNOWN'); });
test('T4 compatible observed used value derives calculated remaining', () => { const q = normalizeQuota({ windows: [quotaWindow({ capacity: 30, used: 7, remaining: null })] }, policy, now); const mismatch = normalizeQuota({ windows: [quotaWindow({ capacity: 30, used: 7, remaining: null, used_unit: 'tokens' })] }, policy, now); assert.equal(q.windows[0].remaining, 23); assert.equal(q.windows[0].confidence, 'CALCULATED'); assert.equal(q.windows[0].watermark, 'GREEN'); assert.equal(mismatch.windows[0].remaining, null); });
test('T5 native units remain distinct and are not converted', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: 'requests', unit: 'requests', capacity: 500, remaining: 400 }), quotaWindow({ window_id: 'credits', unit: 'credits', capacity: 100, remaining: 90 })] }, policy, now); assert.deepEqual(q.windows.map(w => w.unit), ['requests', 'credits']); assert.equal(q.watermark, 'UNKNOWN'); });
test('T6 OpenAI Codex status fixture parses deterministic windows', () => { const result = parseOpenAiCodexStatus({ usage: { windows: [{ id: '5h', unit: 'percent', used: 25, capacity: 100, reset_at: '2026-08-29T04:00:00Z' }] } }); assert.deepEqual(result, [{ window_id: '5h', unit: 'percent', used: 25, capacity: 100, remaining: null, reset_at: '2026-08-29T04:00:00Z', confidence: 'OBSERVED', status: 'KNOWN' }]); });
test('T7 OpenRouter key fixture preserves limit and usage semantics', () => { const result = parseOpenRouterKey({ data: { limit: null, limit_remaining: null, usage: 0, usage_daily: 0, usage_weekly: 0, usage_monthly: 0, limit_reset: null, is_free_tier: false } }); assert.equal(result.length, 4); assert.equal(result[0].unit, 'USD'); assert.equal(result[0].capacity, null); assert.equal(result[0].used, 0); assert.equal(result[0].confidence, 'OBSERVED'); assert.equal(result[0].status, 'UNKNOWN'); });
test('T8 GitHub usage fixture preserves premium request and credit scopes', () => { const result = parseGitHubUsage({ usageItems: [{ product: 'Copilot', sku: 'Copilot Premium Requests', unitType: 'requests', grossQuantity: 17 }, { product: 'Copilot', sku: 'Copilot AI Credits', unitType: 'credits', grossQuantity: 4 }] }); assert.deepEqual(result.map(w => [w.window_id, w.unit, w.used]), [['Copilot Premium Requests', 'requests', 17], ['Copilot AI Credits', 'credits', 4]]); assert.ok(result.every(w => w.remaining === null && w.capacity === null && w.confidence === 'OBSERVED')); });
test('T9 OpenCode Go policy is DECLARED rather than observed', () => { const result = declaredOpenCodeGoPolicy(); assert.deepEqual(result.map(w => [w.window_id, w.capacity, w.unit, w.confidence]), [['5-hour', 12, 'USD', 'DECLARED'], ['weekly', 30, 'USD', 'DECLARED'], ['monthly', 60, 'USD', 'DECLARED']]); assert.ok(result.every(w => w.used === null && w.remaining === null)); });
test('T10 permission failure becomes unavailable unknown evidence', () => { const result = normalizeProviderProbeError({ provider: 'github-copilot', surface: 'billing', status: 403, now }); assert.equal(result.availability, 'AUTH_INSUFFICIENT'); assert.equal(result.quota.status, 'UNKNOWN'); assert.equal(result.quota.remaining, null); assert.notEqual(result.quota.watermark, 'RED'); });
test('T11 authentication readiness cannot create allowance', () => { const result = normalizeRawProviderQuota({ provider: 'openai-codex', surface: 'auth-check', raw: { status: 'ready', authType: 'oauth' }, now, policy }); assert.equal(result.status, 'UNKNOWN'); assert.equal(result.capacity, null); assert.equal(result.remaining, null); });
test('T12 credentials and authorization headers never survive redaction', () => { const raw = { Authorization: 'Bearer secret', access_token: 'secret2', api_key: 'secret3', nested: { cookie: 'secret4' } }; const sanitized = redactProviderOutput(raw); assert.doesNotMatch(sanitized, /secret/); });
test('T13 stale status is computed independently per window', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: 'fresh', observed_at: now }), quotaWindow({ window_id: 'old', observed_at: now - 90_000_000 })] }, policy, now); assert.equal(q.windows.find(w => w.window_id === 'fresh').status, 'KNOWN'); assert.equal(q.windows.find(w => w.window_id === 'old').status, 'STALE'); });
test('T14 expiring allowance changes preference only for useful queued work', () => { const q = normalizeQuota({ windows: [quotaWindow({ reset_at: now + 3_600_000, remaining: 25 })] }, policy, now); const noWork = routeEconomically({ requirement: { trust_domain: 'retrieval', capabilities: ['x'] }, lanes: [lane(q)], policy: createEconomicPolicy({ now }), now, queued_work: false }); const work = routeEconomically({ requirement: { trust_domain: 'retrieval', capabilities: ['x'] }, lanes: [lane(q)], policy: createEconomicPolicy({ now }), now, queued_work: true }); assert.ok(!noWork.reason_codes.includes('USE_IT_OR_LOSE_IT_QUOTA')); assert.ok(work.reason_codes.includes('USE_IT_OR_LOSE_IT_QUOTA')); });
test('T15 authority dominates abundant allowance', () => { const q = normalizeQuota({ windows: [quotaWindow({ capacity: 1_000_000, remaining: 1_000_000 })] }, policy, now); const result = routeEconomically({ requirement: { trust_domain: 'engineering', capabilities: ['x'] }, lanes: [lane(q)], policy: createEconomicPolicy({ now }), now }); assert.equal(result.status, 'DEGRADED'); });
test('T16 observed credits do not open PAYG', () => { const q = normalizeQuota({ windows: [quotaWindow({ capacity: 100, remaining: 100 })] }, policy, now); const result = routeEconomically({ requirement: { trust_domain: 'retrieval', capabilities: ['x'] }, lanes: [{ ...lane(q), lane_id: 'payg', payg: true, marginal_cost: 1 }], policy: createEconomicPolicy({ now }), now }); assert.equal(result.status, 'DEGRADED'); });
test('T17 identical provider observations replay identically', () => { const input = { windows: [quotaWindow({ window_id: 'daily', capacity: 10, remaining: 8 })] }; assert.deepEqual(normalizeQuota(input, policy, now), normalizeQuota(input, policy, now)); });
test('T18 economic router has no provider-specific parser dependency', () => { const source = readFileSync(new URL('../economic-router.mjs', import.meta.url), 'utf8'); assert.doesNotMatch(source, /parse(OpenAi|OpenRouter|GitHub)|openai-codex|openrouter|github-copilot/); });
test('T19 partial observation retains known and unknown windows', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: 'daily', capacity: 10, remaining: 8 }), quotaWindow({ window_id: 'weekly', capacity: 30, remaining: null, status: 'UNKNOWN', confidence: 'UNKNOWN' })] }, policy, now); assert.equal(q.windows.find(w => w.window_id === 'daily').status, 'KNOWN'); assert.equal(q.windows.find(w => w.window_id === 'weekly').status, 'UNKNOWN'); assert.equal(q.watermark, 'UNKNOWN'); });
test('T20 known exhausted window blocks even when another window is UNKNOWN', () => { const q = normalizeQuota({ windows: [quotaWindow({ window_id: 'daily', remaining: 0 }), quotaWindow({ window_id: 'weekly', remaining: null, status: 'UNKNOWN', confidence: 'UNKNOWN' })] }, policy, now); const result = routeEconomically({ requirement: { trust_domain: 'retrieval', capabilities: ['x'] }, lanes: [lane(q)], policy: createEconomicPolicy({ now }), now }); assert.equal(result.status, 'DEGRADED'); assert.ok(result.rejections.some(r => r.reason === 'QUOTA_EXHAUSTED')); });

test('T21 fresh quota observations use bounded cache without polling', () => { let calls = 0; let clock = now; const cache = new BoundedQuotaProbeCache({ probe: () => { calls++; return { value: 'observation' }; }, ttl_ms: 1000, now: () => clock }); assert.equal(cache.observe().cache_status, 'LIVE'); clock += 500; assert.equal(cache.observe().cache_status, 'FRESH_CACHE'); assert.equal(calls, 1); clock += 1001; assert.equal(cache.observe().cache_status, 'LIVE'); assert.equal(calls, 2); });
test('T22 changed window emits one targeted causal event', () => { const before = { lane_id: 'remote', quota: normalizeQuota({ windows: [quotaWindow({ window_id: 'daily', capacity: 100, remaining: 80 })] }, policy, now) }; const after = { lane_id: 'remote', quota: normalizeQuota({ windows: [quotaWindow({ window_id: 'daily', capacity: 100, remaining: 79 })] }, policy, now) }; const event = quotaNotification(before, after); assert.equal(event.type, 'quota.window.changed'); assert.deepEqual(event.window_ids, ['daily']); });
