import test from 'node:test';
import assert from 'node:assert/strict';
import { queryClaimTraceability } from '../../librarian/librarian.mjs';
import { createClaimKnowledgePlane, promoteAuditedClaims, projectClaims, TRAINING_ELIGIBILITY } from '../knowledge-plane.mjs';

const source = { source_id: 'doc:doi:10.48550/arxiv.2210.03629', source_ref: 'corpus/research/react.txt', source_hash: 'abc123', title: 'ReAct' };
const claim = (overrides = {}) => ({ claim_id: 'CLM-001', claim_text: 'Interleaving thoughts and acts improves decisions.', classification: 'SOURCE_FACT', source_id: source.source_id, support_location: 'Abstract', support_type: 'EXPLICIT_SOURCE_PASSAGE', verification_status: 'SUPPORTED', ...overrides });
const plane = () => createClaimKnowledgePlane({ sources: [source] });

test('audited SOURCE_FACT promotes successfully', () => { const r = plane().promote([claim()]); assert.equal(r.promoted.length, 1); assert.equal(r.promoted[0].epistemic_class, 'SOURCE_FACT'); });
test('unsupported claim fails closed', () => { const r = plane().promote([claim({ verification_status: 'UNSUPPORTED' })]); assert.equal(r.rejected[0].reason, 'verification_status must be SUPPORTED'); });
test('UNKNOWN is retained but not promoted as fact', () => { const r = plane().promote([claim({ classification: 'UNKNOWN', verification_status: 'UNKNOWN' })]); assert.equal(r.retained[0].promotion_state, 'RETAINED'); assert.equal(r.retained[0].epistemic_class, 'UNKNOWN'); });
test('DERIVED_SYNTHESIS preserves derived status', () => { const r = plane().promote([claim({ classification: 'DERIVED_SYNTHESIS', verification_status: 'DERIVED_NOT_SOURCE_FACT' })]); assert.equal(r.promoted[0].epistemic_class, 'DERIVED_SYNTHESIS'); assert.equal(r.promoted[0].authority_class, 'DERIVED_KAD_KNOWLEDGE'); });
test('PROJECT_INFERENCE preserves project-specific status', () => { const r = plane().promote([claim({ classification: 'PROJECT_INFERENCE', verification_status: 'DERIVED_NOT_SOURCE_FACT' })]); assert.equal(r.promoted[0].epistemic_class, 'PROJECT_INFERENCE'); });
test('missing provenance fails', () => { const r = plane().promote([claim({ source_id: null })]); assert.equal(r.rejected[0].reason, 'source_id is required'); });
test('broken source linkage fails', () => { const r = plane().promote([claim({ source_id: 'doc:missing' })]); assert.equal(r.rejected[0].reason, 'source linkage is not present'); });
test('duplicate promotion is idempotent', () => { const p = plane(); const first = p.promote([claim()]); const second = p.promote([claim()]); assert.deepEqual(second.promoted, []); assert.equal(second.duplicates[0], 'kp:claim:CLM-001'); assert.deepEqual(p.list(), first.promoted); });
test('canonical record IDs are stable', () => { assert.equal(plane().promote([claim()]).promoted[0].id, 'kp:claim:CLM-001'); });
test('Librarian returns canonical authority and derived references', () => { const p = plane(); const r = p.promote([claim()]); const v = p.projectOpenViking({ available: true }); const answer = queryClaimTraceability('CLM-001', { records: r.promoted, derived: v.entries }); assert.equal(answer.status, 'PASS'); assert.equal(answer.authority, 'AUTHORITATIVE_EVIDENCE'); assert.equal(answer.derived_references.length, 1); });
test('supersession preserves history', () => { const p = plane(); p.promote([claim()]); const r = p.supersede('CLM-001', claim({ claim_id: 'CLM-002', claim_text: 'Updated claim.' })); assert.equal(r.current.id, 'kp:claim:CLM-002'); assert.equal(p.show('CLM-001').acceptance_state, 'SUPERSEDED'); assert.equal(p.history().length, 2); });
test('wiki projection maps back to canonical IDs', () => { const output = projectClaims(plane().promote([claim()]).promoted); assert.match(output.markdown, /kp:claim:CLM-001/); assert.equal(output.records[0].canonical_id, 'kp:claim:CLM-001'); });
test('derived projection cannot mutate canonical state', () => { const p = plane(); const r = p.promote([claim()]); const projection = projectClaims(r.promoted); projection.records[0].epistemic_class = 'SOURCE_FACT'; assert.equal(p.show('CLM-001').epistemic_class, 'SOURCE_FACT'); assert.equal(p.show('CLM-001').authority_class, 'AUTHORITATIVE_EVIDENCE'); });
test('OpenViking unavailable degrades gracefully', () => { const r = plane().projectOpenViking({ available: false }); assert.equal(r.status, 'DEGRADED'); assert.equal(r.canonical_mutation, false); });
test('derived OpenViking entry maps to canonical record', () => { const p = plane(); const r = p.promote([claim()]); const v = p.projectOpenViking({ available: true }); assert.equal(v.entries[0].canonical_id, r.promoted[0].id); });
test('training eligibility cannot erase epistemic class', () => { const r = plane().promote([claim()]).promoted[0]; assert.equal(r.training_eligibility, TRAINING_ELIGIBILITY.TRAIN_ELIGIBLE); assert.equal(r.epistemic_class, 'SOURCE_FACT'); });
test('deterministic repeated projection', () => { const records = plane().promote([claim()]).promoted; assert.equal(JSON.stringify(projectClaims(records)), JSON.stringify(projectClaims(records))); });
test('invalid provenance and UNKNOWN never enter authoritative records', () => { const p = plane(); const r = p.promote([claim({ claim_id: 'bad', source_id: null }), claim({ claim_id: 'unknown', classification: 'UNKNOWN', verification_status: 'UNKNOWN' })]); assert.equal(p.list().length, 0); assert.equal(r.rejected.length, 1); assert.equal(r.retained.length, 1); });
test('seed helper promotes audited ledger and reports counts', () => { const r = promoteAuditedClaims({ claims: [claim(), claim({ claim_id: 'd', classification: 'DERIVED_SYNTHESIS', verification_status: 'DERIVED_NOT_SOURCE_FACT' })], sources: [source] }); assert.deepEqual(r.counts, { considered: 2, source_facts: 1, derived_synthesis: 1, project_inference: 0, unknown_retained: 0, rejected: 0 }); });
