import assert from 'node:assert/strict';
import test from 'node:test';
import { aggregateLineageRemoteTokens } from '../accepted-work-economics.mjs';
import { normalizeWorkerOutput, compileTaskPacket, executeSwarm } from '../swarm.mjs';
import { CapabilityRegistry } from '../local-router.mjs';

const request = { task_id: 'R2', role: 'local_retrieval', trust_domain: 'retrieval', capability: 'repository-fact-finding', question: 'fact', source_paths: ['fixture.md'] };
const valid = { task_id: 'R2', facts: [{ claim: 'Exact fact.', source_path: 'fixture.md', evidence: 'Exact fact.' }], unknowns: [], conflicts: [] };
const controller = { lanes: [{ role: 'controller', id: 'c', provider: 'p', model: 'm', approved: true, payg: false, billing_class: 'SUBSCRIPTION_BACKED', available: true }], execute: async r => ({ plan: { capability: r.capability, source_paths: r.source_paths, question: r.question, max_facts: 1 }, telemetry: { input_tokens: 709, output_tokens: 0 } }) };
function registry() { const r = new CapabilityRegistry(); r.register({ id: 'qwen', local: true, trust_domain: 'retrieval', capabilities: ['repository-fact-finding'], context_window: 2048, available: true }); return r; }
async function run(worker, resume = null) { return executeSwarm({ request, sources: [{ path: 'fixture.md', content: 'Exact fact.' }], controller, registry: registry(), resume, worker: { resource_id: 'qwen', execute: worker } }); }

test('T1/T3 attempt-level usage sums and retains repair', async () => {
  const result = await run(async ({ repair }) => ({ output: repair ? JSON.stringify(valid) : '{bad', telemetry: repair ? { input_tokens: 3, output_tokens: 4, latency_ms: 2 } : { input_tokens: 5, output_tokens: 6, latency_ms: 1 } }));
  assert.deepEqual(result.telemetry.local_attempts.map(a => [a.attempt, a.kind]), [[1, 'initial'], [2, 'repair']]);
  assert.equal(result.telemetry.local_input_tokens_total, 8); assert.equal(result.telemetry.local_output_tokens_total, 10); assert.equal(result.telemetry.local_tokens_total, 18);
});
test('T2 unknown attempt keeps complete totals unknown', async () => { const result = await run(async ({ repair }) => ({ output: repair ? JSON.stringify(valid) : '{bad', telemetry: repair ? { input_tokens: 3, output_tokens: 4 } : { input_tokens: 5 } })); assert.equal(result.telemetry.local_output_tokens_total, null); assert.equal(result.telemetry.local_tokens_total, null); });
test('T4/T5/T6 resume has zero incremental and inherits parent once', async () => { const parent = { schema_version: 'kad-economic-1', episode_id: 'parent', usage: { input_tokens: 709, output_tokens: 0, total_tokens: 709 }, quality: {}, economics: {} }; const recovery = { schema_version: 'kad-economic-1', episode_id: 'recovery', usage: { input_tokens: 0, output_tokens: 0, total_tokens: 0 }, usage_scope: 'INCREMENTAL_ATTEMPT', inherited_parent: { receipt_id: 'parent', receipt_hash: 'p', remote_tokens: 709 } }; assert.equal(aggregateLineageRemoteTokens([parent, recovery]), 709); assert.equal(aggregateLineageRemoteTokens([parent, parent, recovery]), 709); const result = await run(async () => ({ output: JSON.stringify(valid) }), { controller_result: { plan: { capability: request.capability, source_paths: request.source_paths, question: request.question, max_facts: 1 } }, telemetry: { controller_invocations: 1, input_tokens: 709, output_tokens: 0 }, parent_receipt_id: 'parent', parent_receipt_hash: 'p', skip_consumption: true }); assert.equal(result.telemetry.incremental_remote_tokens, 0); assert.equal(result.telemetry.inherited_parent.remote_tokens, 709); });
test('T7 duplicate receipt IDs are not counted twice', () => { const receipt = { schema_version: 'kad-economic-1', episode_id: 'same', usage: { input_tokens: 709, output_tokens: 0, total_tokens: 709 }, quality: {}, economics: {} }; assert.equal(aggregateLineageRemoteTokens([receipt, receipt]), 709); });
test('T8/T9 raw forensic capture is hashed and excluded from exports', () => { const result = normalizeWorkerOutput(`<think>secret</think>${JSON.stringify(valid)}`, { attempt_id: 'a1' }); assert.equal(result.forensic.raw_output_sha256, result.raw_hash); assert.equal(result.forensic.byte_length > 0, true); assert.equal(result.forensic.FOR_FORENSICS_ONLY, true); assert.equal(result.forensic.TRAINING_ELIGIBLE, false); assert.equal(result.forensic.DISTILLATION_ELIGIBLE, false); assert.equal(result.raw, undefined); });
test('T10 provenance identifies exact deterministic boundary', () => { const p = normalizeWorkerOutput(JSON.stringify(valid)).provenance; assert.match(p.normalizer_version, /normalizer/); assert.equal(p.normalizer_source_hash.length, 64); assert.equal(p.validator_hash.length, 64); assert.ok('runtime_commit' in p); });
test('T11/T12 malformed wrappers fail closed', () => { for (const raw of ['<think>x</analysis>' + JSON.stringify(valid), '<think>x</think>', '<think>x<analysis>y</analysis></think>' + JSON.stringify(valid)]) assert.equal(normalizeWorkerOutput(raw).success, false); });
test('T13 multiple candidates remain fail closed', () => { assert.equal(normalizeWorkerOutput(JSON.stringify(valid) + JSON.stringify(valid)).success, false); });
test('T14 semantic errors remain untouched', () => { const wrong = { ...valid, facts: [{ rule: 'not claim', source_path: 'fixture.md', evidence: 'Exact fact.' }] }; assert.deepEqual(normalizeWorkerOutput(JSON.stringify(wrong)).value, wrong); });
test('T15 resume acceptance semantics are explicit', async () => { const result = await run(async () => ({ output: JSON.stringify(valid) }), { controller_result: { plan: { capability: request.capability, source_paths: request.source_paths, question: request.question } }, telemetry: {}, skip_consumption: true, acceptance_semantics: 'CONTROLLER_CONSUMPTION_REQUIRED' }); assert.equal(result.status, 'DEGRADED'); assert.equal(result.failure_reason, 'CONTROLLER_CONSUMPTION_REQUIRED'); });
test('T16 deterministic fixture replay is identical', () => { const raw = JSON.stringify(valid); assert.deepEqual(normalizeWorkerOutput(raw), normalizeWorkerOutput(raw)); });
